/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.PacienteBO;
import DTO.PacienteNuevoDTO;
import DTO.PacienteViejoDTO;
import Entidades.DireccionPaciente;
import Entidades.Paciente;
import Exception.NegocioException;
import Exception.PersistenciaClinicaException;
import configuracion.DependencyInjector;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sonic
 */
public class editarPerfilPaciente extends javax.swing.JFrame {

    private PacienteViejoDTO paciente;

    private PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();
    private dashboardPaciente ventanaPaciente;
    private iniciarSesion ventanaInicio;

    public editarPerfilPaciente(PacienteViejoDTO paciente) {
        this.paciente = paciente;
        initComponents();
        cargarDatosEditar(paciente);
    }

    /**
     * Creates new form editarPerfilPaciente
     */
    public editarPerfilPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldNombre2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldApellidoPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldApellidoMaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fechaNacimientoChooser = new com.toedter.calendar.JDateChooser();
        fieldTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldCalle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldCodigoPostal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldNumeroExterior = new javax.swing.JTextField();
        botonGuardarCambios = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cargarNombres = new javax.swing.JLabel();
        cargarApellidoPaterno = new javax.swing.JLabel();
        cargarApellidoMaterno = new javax.swing.JLabel();
        cargarFechaNacimiento = new javax.swing.JLabel();
        cargarTelefono = new javax.swing.JLabel();
        cargarCorreoElectronico = new javax.swing.JLabel();
        cargarCalle = new javax.swing.JLabel();
        cargarCodigoPostal = new javax.swing.JLabel();
        cargarNumeroExterior = new javax.swing.JLabel();

        fieldNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombre2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Apellido Paterno");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(632, 757));

        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombres:");

        fieldApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldApellidoPaternoActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellido Paterno:");

        fieldApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldApellidoMaternoActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellido Materno:");

        jLabel7.setText("Fecha de Nacimiento:");

        fieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTelefonoActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefono:");

        fieldCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCalleActionPerformed(evt);
            }
        });

        jLabel9.setText("Calle:");

        fieldCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCodigoPostalActionPerformed(evt);
            }
        });

        jLabel10.setText("Codigo Postal:");

        jLabel11.setText("Numero exterior:");

        fieldNumeroExterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumeroExteriorActionPerformed(evt);
            }
        });

        botonGuardarCambios.setText("Guardar Cambios");
        botonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarCambiosActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Editar Perfil");

        jLabel2.setText("Correo Electronico:");

        cargarNombres.setText("nombres");

        cargarApellidoPaterno.setText("apellidoPaterno");

        cargarApellidoMaterno.setText("apellidoMaterno");

        cargarFechaNacimiento.setText("fechaNacimiento");

        cargarTelefono.setText("telefono");

        cargarCorreoElectronico.setText("correElectronico");

        cargarCalle.setText("calle");

        cargarCodigoPostal.setText("codigoPostal");

        cargarNumeroExterior.setText("numeroExterior");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargarNumeroExterior))
                    .addComponent(fieldNumeroExterior, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargarNombres))
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargarApellidoMaterno))
                    .addComponent(fieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargarTelefono))
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargarCalle))
                    .addComponent(fieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cargarApellidoPaterno))
                        .addComponent(fieldApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cargarFechaNacimiento))
                        .addComponent(fechaNacimientoChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cargarCodigoPostal))
                        .addComponent(fieldCodigoPostal, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(fieldEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargarCorreoElectronico)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cargarApellidoPaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cargarNombres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cargarApellidoMaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cargarFechaNacimiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaNacimientoChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(cargarTelefono)
                    .addComponent(cargarCorreoElectronico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldEmail)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cargarCodigoPostal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cargarCalle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cargarNumeroExterior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNumeroExterior, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(botonGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setVentanaPaciente(dashboardPaciente ventanaPaciente) {
        this.ventanaPaciente = ventanaPaciente;
    }

    public void setVentanaInicio(iniciarSesion ventanaInicio) {
        this.ventanaInicio = ventanaInicio;
    }

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApellidoPaternoActionPerformed

    private void fieldNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombre2ActionPerformed

    private void fieldApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApellidoMaternoActionPerformed

    private void fieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTelefonoActionPerformed

    private void fieldCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCalleActionPerformed

    private void fieldCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCodigoPostalActionPerformed

    private void fieldNumeroExteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumeroExteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumeroExteriorActionPerformed

    private void botonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCambiosActionPerformed
        try {
            actualizarPaciente(paciente);
        } catch (PersistenciaClinicaException | NegocioException ex) {
            Logger.getLogger(editarPerfilPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonGuardarCambiosActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        volverDashboardPaciente();
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarPerfilPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarCambios;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel cargarApellidoMaterno;
    private javax.swing.JLabel cargarApellidoPaterno;
    private javax.swing.JLabel cargarCalle;
    private javax.swing.JLabel cargarCodigoPostal;
    private javax.swing.JLabel cargarCorreoElectronico;
    private javax.swing.JLabel cargarFechaNacimiento;
    private javax.swing.JLabel cargarNombres;
    private javax.swing.JLabel cargarNumeroExterior;
    private javax.swing.JLabel cargarTelefono;
    private com.toedter.calendar.JDateChooser fechaNacimientoChooser;
    private javax.swing.JTextField fieldApellidoMaterno;
    private javax.swing.JTextField fieldApellidoPaterno;
    private javax.swing.JTextField fieldCalle;
    private javax.swing.JTextField fieldCodigoPostal;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldNombre2;
    private javax.swing.JTextField fieldNumeroExterior;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
// Actualiza los datos del paciente con la nueva información proporcionada

    public void actualizarPaciente(PacienteViejoDTO paciente) throws PersistenciaClinicaException, NegocioException {
        // Obtiene los datos de los campos de texto en la interfaz
        String nombres = fieldNombre.getText();
        String apellidoPaterno = fieldApellidoPaterno.getText();
        String apellidoMaterno = fieldApellidoMaterno.getText();
        String calle = fieldCalle.getText();
        String numero = fieldNumeroExterior.getText();
        String email = fieldEmail.getText();
        String telefono = fieldTelefono.getText();
        String cp = fieldCodigoPostal.getText();

        // Obtiene la fecha del JDateChooser y la convierte a LocalDate
        java.util.Date fechaNacimientoUtil = fechaNacimientoChooser.getDate();
        LocalDate fechaNacimiento = null;
        if (fechaNacimientoUtil != null) {
            fechaNacimiento = fechaNacimientoUtil.toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
        }

        // Verifica si hay al menos un campo diferente entre los datos anteriores y los nuevos
        boolean hayCambios = !nombres.equals(paciente.getNombres())
                || !apellidoPaterno.equals(paciente.getApellidoPaterno())
                || !apellidoMaterno.equals(paciente.getApellidoMaterno())
                || !calle.equals(paciente.getDireccion().getCalle())
                || !numero.equals(paciente.getDireccion().getNumero())
                || !cp.equals(paciente.getDireccion().getCodigoPostal())
                || !email.equals(paciente.getEmail())
                || !telefono.equals(paciente.getTelefono())
                || (paciente.getFechaNacimiento() != null && !paciente.getFechaNacimiento().equals(fechaNacimiento));

        // Verifica si hay al menos un campo lleno
        boolean hayCampoLleno = !nombres.isEmpty()
                || !apellidoPaterno.isEmpty()
                || !apellidoMaterno.isEmpty()
                || !calle.isEmpty()
                || !numero.isEmpty()
                || !email.isEmpty()
                || !telefono.isEmpty()
                || !cp.isEmpty()
                || (fechaNacimiento != null);

        // Si no hay cambios o no hay campos llenos, muestra un mensaje de error
        if (!hayCambios || !hayCampoLleno) {
            JOptionPane.showMessageDialog(this, "Debe realizar al menos un cambio y llenar al menos un campo.");
            return; // Sale sin actualizar
        }

        // Muestra un mensaje de confirmación antes de realizar la actualización
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "Antes de actualizar, verifique correctamente cada dato ingresado.",
                "¿Actualizar datos?",
                JOptionPane.YES_NO_OPTION
        );

        // Si el usuario acepta, intenta actualizar los datos
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                // Crea el nuevo objeto de dirección y el objeto PacienteViejoDTO con los nuevos datos
                DireccionPaciente direccion = new DireccionPaciente(calle, numero, cp);
                PacienteViejoDTO pacienteActualizado = new PacienteViejoDTO(paciente.getIdPaciente(), direccion, paciente.getUsuario(), nombres, apellidoPaterno, apellidoMaterno, fechaNacimiento, email, telefono);

                // Llama al método para actualizar el paciente en la base de datos
                Paciente exito = pacienteBO.actualizarPaciente(pacienteActualizado);
                if (exito != null) {
                    // Si la actualización es exitosa, muestra un mensaje y limpia los campos
                    JOptionPane.showMessageDialog(this, "El paciente se ha actualizado exitosamente. Vuelva a iniciar sesión para aplicar los cambios.");
                    limpiarCampos();
                    // Si la ventana de inicio no ha sido creada, la crea
                    if (ventanaInicio == null) {
                        ventanaInicio = new iniciarSesion();
                    }

                    ventanaInicio.setVentanaEditarPerfil(this);
                    ventanaInicio.setLocationRelativeTo(null);
                    ventanaInicio.setVisible(true);
                    this.dispose();

                } else {
                    // Si no se pudo actualizar, muestra un mensaje de error
                    JOptionPane.showMessageDialog(this, "ERROR al actualizar al paciente");
                }
            } catch (NegocioException | SQLException ex) {
                // Si ocurre un error, muestra un mensaje con el detalle
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            // Si el usuario cancela, se imprime un mensaje en la consola
            System.out.println("El usuario canceló.");
        }
    }

// Carga los datos del paciente en los campos de edición
    public void cargarDatosEditar(PacienteViejoDTO paciente) {
        cargarNombres.setText(paciente.getNombres());
        cargarApellidoPaterno.setText(paciente.getApellidoPaterno());
        cargarApellidoMaterno.setText(paciente.getApellidoMaterno());
        cargarFechaNacimiento.setText(paciente.getFechaNacimiento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        cargarCorreoElectronico.setText(paciente.getEmail());
        cargarTelefono.setText(paciente.getTelefono());
        cargarCalle.setText(paciente.getDireccion().getCalle());
        cargarCodigoPostal.setText(paciente.getDireccion().getCodigoPostal());
        cargarNumeroExterior.setText(paciente.getDireccion().getNumero());
    }

// Vuelve a la ventana principal del paciente (dashboard)
    public void volverDashboardPaciente() {
        if (ventanaPaciente == null) {
            ventanaPaciente = new dashboardPaciente();
        }

        ventanaPaciente.setVentanaEditarPerfil(this);
        ventanaPaciente.setLocationRelativeTo(null);
        ventanaPaciente.setVisible(true);
        this.dispose();
    }

// Limpia todos los campos de entrada en la interfaz
    public void limpiarCampos() {
        // Limpia los campos de texto
        fieldNombre.setText("");
        fieldApellidoPaterno.setText("");
        fieldApellidoMaterno.setText("");
        fieldCalle.setText("");
        fieldNumeroExterior.setText("");
        fieldTelefono.setText("");
        fieldCodigoPostal.setText("");

        // Reinicia la fecha
        fechaNacimientoChooser.setDate(null);
    }
}
